openapi: 3.0.1
info:
  title: Access Service API
  version: 0.0.2
  contact:
    email: c.bay@zbw.eu
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
tags:
  - name: ItemRest
    description: A bibliographic item
paths:
  /item:
    $ref: 'item.api.yaml#/item'
  /item/{id}:
    $ref: 'item.api.yaml#/item-id'
  /item/list:
    $ref: 'item.api.yaml#/item-list'


components:
  schemas:
    ItemRest:
      $ref: 'item.model.yaml#/ItemRest'
