openapi: 3.0.1
info:
  title: Access Service API
  version: 0.1.0
  contact:
    email: c.bay@zbw.eu
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
tags:
  - name: ItemRest
    description: A bibliographic item
paths:
  /item:
    $ref: 'item.api.yaml#/item'
  /item/list:
    $ref: 'item.api.yaml#/item-list'
  /item/metadata/{metadata-id}:
    $ref: 'item.api.yaml#/item-metadata'
  /item/right/{right-id}:
    $ref: 'item.api.yaml#/item-right'
  /item/count/right/{right-id}:
    $ref: 'item.api.yaml#/item-count-right'
  /item/{metadata-id}/{right-id}:
    $ref: 'item.api.yaml#/item-deletion'
  /metadata:
    $ref: 'metadata.api.yaml#/metadata'
  /metadata/{id}:
    $ref: 'metadata.api.yaml#/metadata-id'
  /metadata/list:
    $ref: 'metadata.api.yaml#/metadata-list'
  /right:
    $ref: 'right.api.yaml#/right'
  /right/{id}:
    $ref: 'right.api.yaml#/right-id'
  /users/login:
    $ref: 'users.api.yaml#/login'
  /users/register:
    $ref: 'users.api.yaml#/register'

components:
  schemas:
    ItemRest:
      $ref: 'item.model.yaml#/ItemRest'
    MetadataRest:
      $ref: 'metadata.model.yaml#/MetadataRest'
    RightRest:
      $ref: 'item.model.yaml#/RightRest'